### ISSUE TITLE
命令与参数的母语化

### ISSUE THREAD

**Issue by nobodxbodon** [StepfenShawn/Cantonese#15]
刚看到 to_web 等参数 (complie 好像是拼写笔误？），不妨考虑也母语化，比如 [木兰重现里用的](https://gitee.com/MulanRevive/mulan-rework/blob/master/%E6%9C%A8%E5%85%B0/%E4%B8%AD.py#L14)：
```
 --版本,         -版   显示版本
 --python变木兰, -兰   将 Python 源码转换为木兰源码
 --语法树,       -树   语法树信息
```
对了在 pypi 发布的时候可以把命令也母语化，像这样：
```
    entry_points = {
        "console_scripts": ['木兰 = 木兰.中:中']
        },
```
就可以运行 `$ 木兰` 了。

**Comment by StepfenShawn** [comment]
已更新！
