### ISSUE TITLE
没有做参数检查

### ISSUE THREAD

**Issue by RonYoung666** [StepfenShawn/Cantonese#2]
python3 cantonese.py 
Traceback (most recent call last):
  File "cantonese.py", line 702, in <module>
    main()
  File "cantonese.py", line 690, in main
    with open(sys.argv[1], encoding = "utf-8") as f:
IndexError: list index out of range

**Comment by StepfenShawn** [comment]
已解决 : ) 
https://github.com/StepfenShawn/Cantonese/commit/ad126f9a22ed4cd86eea87bd7a0dde37143e355a
感谢你的issue!
