### ISSUE TITLE
建议加到esoteric-programming-language和esoteric-language分区里

### ISSUE THREAD

**Issue by Sherlockcxk** [StepfenShawn/Cantonese#22]
因为很多人觉得这个语言不实用，没意义，所以加到这个分区可以让喷子们闭嘴😂

**Comment by nobodxbodon** [comment]
语法、报错信息等等使用非英文并不意味着它不能成为实用编程语言。
粤语是亿万人的母语，在量级上与日语、法语相当。日、法都有实用化的母语编程语言。
中文编程语言也可与粤语编程语言互相借鉴、共同发展。
自己贴上“小众”语言的标签是画地为牢，更是遂了某些唱衰非英文母语编程语言的人的意（比如号称“不是英文编程语言就只是玩具语言”等等）
