### ISSUE TITLE
`six` package dependency error

### ISSUE THREAD

**Issue by dosentmatter** [StepfenShawn/Cantonese#52]
Hello, after installing `Cantonese`, it fails to run because of the [`import six`](https://github.com/StepfenShawn/Cantonese/blob/3072e3b346225cf2b62538fb6823ae32bee165a6/src/stack_vm.py#L9) that isn't included in your [list of dependencies](https://github.com/StepfenShawn/Cantonese/blob/4870538b948d5a03d2a83b72febeb5bcf2df36f6/setup.cfg#L31-L34).
https://github.com/StepfenShawn/Cantonese/blob/3072e3b346225cf2b62538fb6823ae32bee165a6/src/stack_vm.py#L9

https://github.com/StepfenShawn/Cantonese/blob/4870538b948d5a03d2a83b72febeb5bcf2df36f6/setup.cfg#L31-L34

You only support Python 3 in [`setup.cfg`](https://github.com/StepfenShawn/Cantonese/blob/4870538b948d5a03d2a83b72febeb5bcf2df36f6/setup.cfg#L30) and the [README](https://github.com/StepfenShawn/Cantonese/blob/3072e3b346225cf2b62538fb6823ae32bee165a6/README.md?plain=1#L323), so it doesn't look like you would need `six` for Python 2 interoperability.
https://github.com/StepfenShawn/Cantonese/blob/4870538b948d5a03d2a83b72febeb5bcf2df36f6/setup.cfg#L30

It doesn't seem like you are using `six` at all. Can we delete the [`import six`](https://github.com/StepfenShawn/Cantonese/blob/3072e3b346225cf2b62538fb6823ae32bee165a6/src/stack_vm.py#L9) line?

```
% Cantonese
Traceback (most recent call last):
  File "/Users/dosentmatter/.pyenv/versions/3.9.6/bin/Cantonese", line 5, in <module>
    from src.cantonese import main
  File "/Users/dosentmatter/.pyenv/versions/3.9.6/lib/python3.9/site-packages/src/cantonese.py", line 12, in <module>
    from src.stack_vm import *
  File "/Users/dosentmatter/.pyenv/versions/3.9.6/lib/python3.9/site-packages/src/stack_vm.py", line 9, in <module>
    import six
ModuleNotFoundError: No module named 'six'
```

The workaround is to `pip install six`, but this shouldn't be necessary.

**Comment by StepfenShawn** [comment]
OK, I will delete it in the next version.

**Comment by dosentmatter** [comment]
Thanks for the fix @StepfenShawn.

Deleted in [this commit](https://github.com/StepfenShawn/Cantonese/commit/79d9a1f40bde0db716608e3c43862c4ae4e08fcf#diff-069829741f4d739cf3c56e17deb8868914d939fd5144d01223805cbabe129847L9)
